name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 9
        uses: actions/setup-java@v3
        with:
          java-version: '9'
          distribution: 'zulu'
          cache: maven
      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode test
